set(CMAKE_SYSTEM_NAME "Linux")
set(CMAKE_SYSTEM_PROCESSOR "aarch64")
set(CMAKE_HOST_SYSTEM_PROCESSOR "aarch64")

#SET(CMAKE_CROSSCOMPILING TRUE)

set(tools "/usr")
SET(TOOLS_HEAD "${tools}/bin/aarch64-linux-gnu")
set(CMAKE_C_COMPILER "${TOOLS_HEAD}-gcc-11")
set(CMAKE_CXX_COMPILER "${TOOLS_HEAD}-g++-11")
#SET(CMAKE_GFORTRAN  "${TOOLS_HEAD}-gfortran")
SET(CMAKE_AR "${TOOLS_HEAD}-ar")
SET(CMAKE_AS "${TOOLS_HEAD}-as")
SET(CMAKE_LD "${TOOLS_HEAD}-ld")
SET(CMAKE_NM "${TOOLS_HEAD}-nm")
SET(CMAKE_STRIP "${TOOLS_HEAD}-strip")

SET(CMAKE_FIND_ROOT_PATH "${tools}/aarch64-linux-gnu")
set(CMAKE_HOST_TAGER --host=aarch64-linux-gnu)



#CMAKE_C_FLAGS = 
#CMAKE_C_FLAGS_DEBUG = -g
#CMAKE_C_FLAGS_MINSIZEREL = -Os -DNDEBUG
#CMAKE_C_FLAGS_RELEASE = -O3 -DNDEBUG
#CMAKE_C_FLAGS_RELWITHDEBINFO = -O2 -g -DNDEBUG

#CMAKE_CXX_FLAGS = 
#CMAKE_CXX_FLAGS_DEBUG = -g
#CMAKE_CXX_FLAGS_MINSIZEREL = -Os -DNDEBUG
#CMAKE_CXX_FLAGS_RELEASE = -O3 -DNDEBUG
#CMAKE_CXX_FLAGS_RELWITHDEBINFO = -O2 -g -DNDEBUG

#message("2222222222 CMAKE_CXX_COMPILER is ${CMAKE_CXX_COMPILER}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)